### PR TITLE
Skip enforcer checks for the parent

### PR DESCRIPTION
**Pull request by delanym**
Set the phase of the enforcer-rules execution to none on the parent pom only.

### CODE REVIEW

**Comment by io7m** [comment]
Hello!

Thanks for this... I'm not completely sure about the correctness of this though. Are you sure this doesn't just disable the enforcer plugin for child modules?

I don't have time to test it right now, but I'll be happy to merge this if you can show that the enforcer still runs for modules that inherit this.

**Comment by io7m** [comment]
Another thing to consider is that most projects are actually inheriting from the `com.io7m.primogenitor.full` or `com.io7m.primogenitor.lite` modules.

**Comment by delanym** [comment]
The plugin isn't actually disabled its just set to run in the "none" phase (for the root pom only).

You can test with `mvn install --fae`

I suggest you move the semantic versioning checks to their own profile so this can be switched off when a project is new - its very annoying otherwise. You can leave it on by default. The first build will need to include `-Dnew`

```
<profile>
  <id>semantic</id>
  <activation>
    <property>
      <name>!new</name>
    </property>
  </activation>
```

**Comment by io7m** [comment]
Thanks!

**Pull request merged**
